add_newline = false

format = "$username$hostname $directory$git_branch$git_status$kubernetes $character"

[line_break]
disabled = true

[kubernetes]
disabled = false
format = "[$symbol$context(/$namespace)]($style) "
symbol = "☸ "
